# Generated by Django 2.1.7 on 2019-03-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tw_id', models.CharField(max_length=255)),
                ('tw_username', models.CharField(max_length=255)),
                ('tw_lang', models.CharField(max_length=255)),
                ('tw_date', models.DateField()),
                ('tw_text', models.TextField()),
            ],
        ),
    ]
