# Generated by Django 2.1.7 on 2019-03-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slappy', '0002_auto_20190317_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tw_date',
            field=models.CharField(max_length=255),
        ),
    ]
